# Generated by Django 4.2 on 2024-06-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('middleName', models.CharField(max_length=64)),
                ('birthDate', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
                ('citizenship', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('contacts', models.CharField(max_length=64)),
                ('about', models.CharField(max_length=64)),
                ('avatar', models.CharField(max_length=64)),
            ],
        ),
    ]
